apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "db-migrations.fullname" . }}
  labels:
    {{- include "db-migrations.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      initContainers: # Wait for POSTGRES pod to initalise before running migrations - otherwise job will fail.
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z -v -w30 {{ .Values.postgres.host }} {{ .Values.postgres.port }}; do
                echo "Waiting for Postgres..."
                sleep 3
              done
      containers:
        - name: migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["npm", "run", "migrate"]
          {{- with .Values.env }}
          env:
            {{- range . }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
